name: isolate_manager
description: Create multiple long-lived isolates for the Functions, supports Worker on the Web (with the effective generator) and WASM compilation.
version: 6.0.0-rc.2
homepage: https://github.com/lamnhan066/isolate_manager/tree/v6.0.0

topics:
  - isolate
  - worker
  - concurrent

environment:
  sdk: ^3.4.0

dependencies:
  stream_channel: ^2.1.2
  web: ^1.0.0
  analyzer: ^6.0.0
  path: ^1.9.0
  args: ^2.5.0

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
