name: isolate_manager
description: Create multiple long-lived (keep it active to send and receive data) isolates for a function, supports Worker and WASM on the Web.
version: 4.3.0-rc.3
homepage: https://github.com/lamnhan066/isolate_manager

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  isolate_contactor: 4.2.0-rc.4
  web: ^0.5.1

dev_dependencies:
  test: ^1.25.4
  lints: ^3.0.0
