name: isolate_manager
description: Create multiple long-lived isolates for the Functions, supports Worker on the Web (with the effective generator) and WASM compilation.
version: 5.1.0-rc
homepage: https://github.com/lamnhan066/isolate_manager

environment:
  sdk: ^3.3.0

dependencies:
  stream_channel: ^2.1.2
  web: ^0.5.1
  analyzer: ">=5.12.0 <7.0.0"
  path: ^1.9.0
  args: ^2.5.0

dev_dependencies:
  test: ^1.25.7
  lints: ^4.0.0
