name: isolate_manager
description: Create multiple long-lived isolates for a function (keep it active to send and receive data), supports Worker and WASM on the Web.
version: 5.0.0-rc.9
homepage: https://github.com/lamnhan066/isolate_manager/tree/beta

environment:
  sdk: ^3.3.0

dependencies:
  stream_channel: ^2.1.1
  web: ^0.5.1
  analyzer: ">=5.12.0 <7.0.0"
  path: ^1.9.0
  args: ^2.4.2

dev_dependencies:
  test: ^1.25.4
  lints: ^4.0.0
  build_runner: ^2.0.0
