name: isolate_manager
description: Create multiple long-lived isolates for the Functions, supports Worker on the Web (with the effective generator) and WASM compilation.
version: 6.0.0-rc.7
homepage: https://github.com/lamnhan066/isolate_manager/tree/v6.0.0

topics:
  - isolate
  - worker
  - concurrent
  - pool

environment:
  sdk: ^3.4.0

dependencies:
  analyzer: ^6.5.0
  args: ^2.5.0
  equatable: ^2.0.5
  path: ^1.9.0
  stream_channel: ^2.1.0
  web: ^1.0.0

dev_dependencies:
  coverage: ^1.10.0
  test: ^1.25.8
  very_good_analysis: ^6.0.0
